name: Test jupyter notebook tutorials

on:
  push:
    branches: 
      - main # only rerun tutorials when making PRs or changing main
      - v3
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install jupyter setuptools
    - name: Install orbitize
      run: |
        python -m pip install -r .
    - name: Run tutorial notebooks
      run: |
        echo $PATH
        pip list
        jupyter execute docs/tutorials/*.ipynb
      
